/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dheerajv' at '7/12/16 3:18 PM' with Gradle 2.14
 *
 * @author dheerajv, @date 7/12/16 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
